name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Build and push Docker images to Github Container Registry
      uses: fatjyc/push-gcr-action@v2.0
      with:
            user: ${{ github.repository_owner }}
            token: ${{ secrets.GITHUBTOKEN }}
            

