name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    -
      name: Build and push Docker images to Github Container Registry
      uses: fatjyc/push-gcr-action@v2.0
      with:
            user: ${{ user }}
            token: ${{ secrets.GITHUBTOKEN }}
            tagUseBranchNameWhenPush: ${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}

